DROP DATABASE IF EXISTS `data_api_db`;
CREATE DATABASE `data_api_db`
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;

USE 'mysql';
GRANT ALL PRIVILEGES ON data_api_db.* TO 'rahul'@'localhost' IDENTIFIED BY 'magic1'

WITH GRANT OPTION;
FLUSH PRIVILEGES;