# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-06 12:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPermit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationid', models.BigIntegerField(default=0)),
                ('applicant', models.CharField(blank=True, default='', max_length=100)),
                ('facilitytype', models.CharField(blank=True, default='', max_length=100)),
                ('cnn', models.BigIntegerField(default=0)),
                ('locationdescription', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('blocklot', models.CharField(blank=True, default='', max_length=100)),
                ('block', models.CharField(blank=True, default='', max_length=100)),
                ('lot', models.CharField(blank=True, default='', max_length=100)),
                ('permit', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('fooditems', models.CharField(blank=True, default='', max_length=100)),
                ('x', models.DecimalField(decimal_places=3, max_digits=12)),
                ('y', models.DecimalField(decimal_places=3, max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=18)),
                ('schedule', models.CharField(blank=True, default='', max_length=100)),
                ('dayshours', models.CharField(blank=True, default='', max_length=100)),
                ('noisent', models.DateField(default=datetime.date.today)),
                ('approved', models.DateField(default=datetime.date.today)),
                ('received', models.DateField(default=datetime.date.today)),
                ('priorpermit', models.BooleanField()),
                ('expirationdate', models.DateField(default=datetime.date.today)),
            ],
            options={
                'ordering': ('locationid',),
            },
        ),
    ]
