# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-06 17:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpermit',
            name='noisent',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
