# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-07 10:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20170706_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodpermit',
            name='expirationdate',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='foodpermit',
            name='x',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='foodpermit',
            name='y',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
    ]
